export type WordEntry = { word: string; hint: string };

export const WORDS_EN: WordEntry[] = [
  { word: "BRAIN",   hint: "The organ inside your head that controls everything 🧠" },
  { word: "SMILE",   hint: "What your face does when you are happy 😊" },
  { word: "MUSIC",   hint: "Beautiful sounds you listen to 🎵" },
  { word: "HEART",   hint: "The organ that pumps blood and feels love ❤️" },
  { word: "LIGHT",   hint: "What the sun gives us every morning ☀️" },
  { word: "PEACE",   hint: "A calm and quiet feeling inside 🕊️" },
  { word: "GRACE",   hint: "A quality of moving or behaving with elegance 🌸" },
  { word: "FAITH",   hint: "Trust and belief in something you cannot see 🙏" },
  { word: "BLOOM",   hint: "When a flower opens up 🌺" },
  { word: "CLOUD",   hint: "White or grey shapes in the sky ☁️" },
  { word: "DREAM",   hint: "What your mind creates while you sleep 💭" },
  { word: "EARTH",   hint: "The planet we all live on 🌍" },
  { word: "FLAME",   hint: "The glowing part of a fire 🔥" },
  { word: "FRUIT",   hint: "Sweet food that grows on trees 🍎" },
  { word: "GLASS",   hint: "A transparent material used in windows 🪟" },
  { word: "HONEY",   hint: "Sweet golden liquid made by bees 🍯" },
  { word: "IVORY",   hint: "A creamy white colour 🤍" },
  { word: "JEWEL",   hint: "A precious sparkling stone 💎" },
  { word: "KNEEL",   hint: "To go down on one or both knees 🙏" },
  { word: "LEMON",   hint: "A yellow sour citrus fruit 🍋" },
  { word: "MAPLE",   hint: "A tree known for its beautiful autumn leaves 🍁" },
  { word: "NIGHT",   hint: "The dark part of the day when stars come out 🌙" },
  { word: "OCEAN",   hint: "A very large body of salt water 🌊" },
  { word: "PETAL",   hint: "The colourful leaf-like part of a flower 🌸" },
  { word: "QUIET",   hint: "Without noise or sound 🤫" },
  { word: "RIVER",   hint: "A large stream of water that flows 🏞️" },
  { word: "STONE",   hint: "A small piece of rock 🪨" },
  { word: "SUGAR",   hint: "A sweet white crystal used in cooking 🍬" },
  { word: "TIGER",   hint: "A large striped wild cat 🐯" },
  { word: "UMBRA",   hint: "The dark shadow made during an eclipse 🌑" },
  { word: "VIOLA",   hint: "A musical instrument like a large violin 🎻" },
  { word: "WATER",   hint: "The clear liquid we drink every day 💧" },
  { word: "XEROX",   hint: "A common word for a photocopy machine 📄" },
  { word: "YIELD",   hint: "To give way or produce something 🌾" },
  { word: "ZEBRA",   hint: "A black and white striped African animal 🦓" },
  { word: "ANGEL",   hint: "A heavenly being in many religions 👼" },
  { word: "BRAVE",   hint: "Having courage in difficult times 🦁" },
  { word: "CANDY",   hint: "A sweet treat loved by children 🍭" },
  { word: "DANCE",   hint: "Moving your body to music 💃" },
  { word: "EAGLE",   hint: "A powerful bird that soars high in the sky 🦅" },
  { word: "FAIRY",   hint: "A tiny magical creature with wings 🧚" },
  { word: "GIANT",   hint: "Something extremely large in size 🏔️" },
  { word: "HAPPY",   hint: "Feeling joy and contentment 😄" },
  { word: "IMAGE",   hint: "A picture or reflection of something 🖼️" },
  { word: "JOLLY",   hint: "Full of fun and laughter 🎉" },
  { word: "KAYAK",   hint: "A small narrow boat paddled with a double-ended oar 🚣" },
  { word: "LILAC",   hint: "A light purple colour like a spring flower 💜" },
  { word: "MAGIC",   hint: "The power to make wonderful things happen ✨" },
  { word: "NOBLE",   hint: "Having great character and dignity 👑" },
  { word: "OLIVE",   hint: "A small fruit that gives us cooking oil 🫒" },
  { word: "PIANO",   hint: "A large musical instrument with black and white keys 🎹" },
  { word: "QUEEN",   hint: "A female ruler of a kingdom 👸" },
  { word: "ROBIN",   hint: "A small bird with a red breast 🐦" },
  { word: "SOLAR",   hint: "Related to the sun ☀️" },
  { word: "TULIP",   hint: "A beautiful cup-shaped spring flower 🌷" },
  { word: "UNITY",   hint: "Being together and working as one 🤝" },
  { word: "VIVID",   hint: "Very bright and clear in colour 🌈" },
  { word: "WALTZ",   hint: "An elegant ballroom dance 💃" },
  { word: "XENON",   hint: "A rare glowing gas used in lights 💡" },
  { word: "YACHT",   hint: "A large sailing or motor boat ⛵" },
  // 6-letter words
  { word: "BRIDGE", hint: "A structure that lets you cross over water or a gap 🌉" },
  { word: "CANDLE", hint: "A wax stick with a wick that gives light when burned 🕯️" },
  { word: "FLOWER", hint: "The colourful part of a plant that blooms 🌸" },
  { word: "GARDEN", hint: "A place where flowers and vegetables grow 🌻" },
  { word: "GOLDEN", hint: "Coloured like gold, bright and warm 🌟" },
  { word: "HUMBLE", hint: "Being modest and not proud 🙏" },
  { word: "JOYFUL", hint: "Full of great happiness 😄" },
  { word: "KINDLY", hint: "In a warm and friendly manner 💛" },
  { word: "LOVELY", hint: "Very attractive and pleasant 🌺" },
  { word: "MELLOW", hint: "Soft, gentle, and relaxed 🍂" },
  { word: "NECTAR", hint: "Sweet liquid found in flowers, loved by bees 🍯" },
  { word: "ORANGE", hint: "A round citrus fruit or a warm colour 🍊" },
  { word: "PURPLE", hint: "A colour made by mixing red and blue 💜" },
  { word: "RADIANT",hint: "Glowing brightly with light or happiness ✨" },
  { word: "SILVER", hint: "A shiny grey precious metal 🪙" },
  { word: "TENDER", hint: "Gentle, loving, and soft 💗" },
  { word: "BREEZE", hint: "A gentle and pleasant wind 🌬️" },
  { word: "CHERRY", hint: "A small round red or dark fruit 🍒" },
  { word: "SERENE", hint: "Calm, peaceful, and undisturbed 🌅" },
  { word: "FRIEND", hint: "Someone you love spending time with 🤝" },
  { word: "MEMORY", hint: "When you remember something from the past 💭" },
  { word: "WISDOM", hint: "Knowledge gained from many years of life 📚" },
];

export const WORDS_HI: WordEntry[] = [
  { word: "KHUSHI",    hint: "खुशी — जब मन में आनंद हो 😊" },
  { word: "PYAAR",     hint: "प्यार — जो दिल से महसूस होता है ❤️" },
  { word: "SHANTI",    hint: "शांति — मन का सुकून 🕊️" },
  { word: "UMEED",     hint: "उम्मीद — भविष्य पर भरोसा 🌟" },
  { word: "SUNDAR",    hint: "सुंदर — जो देखने में अच्छा लगे 🌸" },
  { word: "AASHA",     hint: "आशा — एक सुंदर उम्मीद 🌈" },
  { word: "PREM",      hint: "प्रेम — दिल की गहरी भावना ❤️" },
  { word: "SEVA",      hint: "सेवा — दूसरों की मदद करना 🙏" },
  { word: "DHARM",     hint: "धर्म — जो सही और न्यायपूर्ण हो 🌺" },
  { word: "SAHAS",     hint: "साहस — मुश्किल में हिम्मत 🦁" },
  { word: "MILAN",     hint: "मिलन — प्रियजनों से मुलाकात 🤝" },
  { word: "NAMAN",     hint: "नमन — सम्मान से झुकना 🙏" },
  { word: "PAWAN",     hint: "पवन — ताज़ी हवा का झोंका 🌬️" },
  { word: "RATAN",     hint: "रतन — बहुमूल्य रत्न 💎" },
  { word: "SAGAR",     hint: "सागर — विशाल समुद्र 🌊" },
  { word: "TARUN",     hint: "तरुण — जवान और ऊर्जा से भरा 💪" },
  { word: "UTSAV",     hint: "उत्सव — खुशी का त्यौहार 🎉" },
  { word: "VAYU",      hint: "वायु — हमारे चारों ओर की हवा 💨" },
  { word: "YATRA",     hint: "यात्रा — एक सुंदर सफर 🚶" },
  { word: "BHOJAN",    hint: "भोजन — खाना जो हमें ताकत देता है 🍛" },
  { word: "CHAMAK",    hint: "चमक — रोशनी की झलक ✨" },
  { word: "DEEPAK",    hint: "दीपक — छोटा दिया जो अँधेरा दूर करे 🪔" },
  { word: "FULWAR",    hint: "फूलवार — फूलों का बगीचा 🌻" },
  { word: "GAGAN",     hint: "गगन — आसमान जो हमेशा ऊपर है 🌤️" },
  { word: "ISHWAR",    hint: "ईश्वर — जो सबका पालन करता है 🙏" },
  { word: "KAVITA",    hint: "कविता — सुंदर भावों की रचना 📝" },
  { word: "LALIMA",    hint: "लालिमा — सुबह का लाल रंग 🌅" },
  { word: "MAUSAM",    hint: "मौसम — बाहर का मौसम कैसा है? 🌦️" },
  { word: "NISHTHA",   hint: "निष्ठा — सच्ची लगन और ईमानदारी 💫" },
  { word: "PAHAD",     hint: "पहाड़ — ऊँची और मजबूत पर्वत-चोटी ⛰️" },
];

export const WORDS_MR: WordEntry[] = [
  { word: "ANAND",     hint: "आनंद — मनातील आनंद 😊" },
  { word: "PREM",      hint: "प्रेम — हृदयातून जाणवते ❤️" },
  { word: "SHANTI",    hint: "शांती — मनाची शांतता 🕊️" },
  { word: "AASHA",     hint: "आशा — भविष्यावरचा विश्वास 🌟" },
  { word: "SUNDAR",    hint: "सुंदर — पाहायला छान वाटते 🌸" },
  { word: "SEVA",      hint: "सेवा — इतरांना मदत करणे 🙏" },
  { word: "NAVI",      hint: "नवी — एखादी नवीन गोष्ट 🌱" },
  { word: "GEET",      hint: "गीत — सुंदर गाणे 🎵" },
  { word: "PHUL",      hint: "फूल — उमललेले फूल 🌺" },
  { word: "NADEE",     hint: "नदी — वाहती नदी 🏞️" },
  { word: "PAANI",     hint: "पाणी — जीवन देणारे पाणी 💧" },
  { word: "AAKAI",     hint: "आकाई — आकाशाचे रूप 🌤️" },
  { word: "GHAR",      hint: "घर — आपले प्रिय घर 🏡" },
  { word: "DIVA",      hint: "दिवा — अंधारात प्रकाश देणारा दिवा 🪔" },
  { word: "WARA",      hint: "वारा — थंड आणि ताजा वारा 🌬️" },
  { word: "PRITI",     hint: "प्रीती — मनातील माया आणि प्रेम 💗" },
  { word: "SAHIL",     hint: "साहिल — समुद्राचा किनारा 🌊" },
  { word: "VAAT",      hint: "वाट — पुढे जाण्याचा मार्ग 🛤️" },
  { word: "USHA",      hint: "उषा — पहाटेचा सुंदर उजेड 🌅" },
  { word: "TAARA",     hint: "तारा — रात्री चमकणारा तारा ⭐" },
  { word: "MATI",      hint: "माती — सुगंधी ओली माती 🌱" },
  { word: "KRIPA",     hint: "कृपा — दुसऱ्यावर केलेली दया 💛" },
  { word: "PAAN",      hint: "पान — झाडाचे हिरवे पान 🍃" },
  { word: "DHYAN",     hint: "ध्यान — मन शांत ठेवण्याचा सराव 🧘" },
  { word: "BHET",      hint: "भेट — प्रिय व्यक्तीची भेट 🤝" },
  { word: "GAVHA",     hint: "गव्हा — सोनेरी गव्हाचे शेत 🌾" },
  { word: "NEEM",      hint: "नीम — औषधी नीमाचे झाड 🌿" },
  { word: "AAMBA",     hint: "आंबा — गोड आणि रसाळ आंबा 🥭" },
  { word: "RAAN",      hint: "रान — हिरवेगार रान आणि शेत 🌳" },
  { word: "PAVSA",     hint: "पाऊस — मातीला सुगंध देणारा पाऊस 🌧️" },
];
